//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public enum MikanClientFeatures {
  RenderTarget_NONE = 0,
  RenderTarget_RGB24 = 1 << 0,
  RenderTarget_RGBA32 = 1 << 1,
  RenderTarget_BGRA32 = 1 << 2,
  RenderTarget_DEPTH16 = 1 << 3,
  RenderTarget_DEPTH32 = 1 << 4
}

}
