//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanVideoSourceMode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanVideoSourceMode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanVideoSourceMode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanVideoSourceMode obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanVideoSourceMode() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanVideoSourceMode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MikanVideoSourceType video_source_type {
    set {
      MikanClientPINVOKE.MikanVideoSourceMode_video_source_type_set(swigCPtr, (int)value);
    } 
    get {
      MikanVideoSourceType ret = (MikanVideoSourceType)MikanClientPINVOKE.MikanVideoSourceMode_video_source_type_get(swigCPtr);
      return ret;
    } 
  }

  public MikanVideoSourceApi video_source_api {
    set {
      MikanClientPINVOKE.MikanVideoSourceMode_video_source_api_set(swigCPtr, (int)value);
    } 
    get {
      MikanVideoSourceApi ret = (MikanVideoSourceApi)MikanClientPINVOKE.MikanVideoSourceMode_video_source_api_get(swigCPtr);
      return ret;
    } 
  }

  public string device_path {
    set {
      MikanClientPINVOKE.MikanVideoSourceMode_device_path_set(swigCPtr, value);
    } 
    get {
      string ret = MikanClientPINVOKE.MikanVideoSourceMode_device_path_get(swigCPtr);
      return ret;
    } 
  }

  public string video_mode_name {
    set {
      MikanClientPINVOKE.MikanVideoSourceMode_video_mode_name_set(swigCPtr, value);
    } 
    get {
      string ret = MikanClientPINVOKE.MikanVideoSourceMode_video_mode_name_get(swigCPtr);
      return ret;
    } 
  }

  public int resolution_x {
    set {
      MikanClientPINVOKE.MikanVideoSourceMode_resolution_x_set(swigCPtr, value);
    } 
    get {
      int ret = MikanClientPINVOKE.MikanVideoSourceMode_resolution_x_get(swigCPtr);
      return ret;
    } 
  }

  public int resolution_y {
    set {
      MikanClientPINVOKE.MikanVideoSourceMode_resolution_y_set(swigCPtr, value);
    } 
    get {
      int ret = MikanClientPINVOKE.MikanVideoSourceMode_resolution_y_get(swigCPtr);
      return ret;
    } 
  }

  public float frame_rate {
    set {
      MikanClientPINVOKE.MikanVideoSourceMode_frame_rate_set(swigCPtr, value);
    } 
    get {
      float ret = MikanClientPINVOKE.MikanVideoSourceMode_frame_rate_get(swigCPtr);
      return ret;
    } 
  }

  public MikanVideoSourceMode() : this(MikanClientPINVOKE.new_MikanVideoSourceMode(), true) {
  }

}

}
