//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanVector3d : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanVector3d(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanVector3d obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanVector3d obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanVector3d() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanVector3d(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double x {
    set {
      MikanClientPINVOKE.MikanVector3d_x_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanVector3d_x_get(swigCPtr);
      return ret;
    } 
  }

  public double y {
    set {
      MikanClientPINVOKE.MikanVector3d_y_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanVector3d_y_get(swigCPtr);
      return ret;
    } 
  }

  public double z {
    set {
      MikanClientPINVOKE.MikanVector3d_z_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanVector3d_z_get(swigCPtr);
      return ret;
    } 
  }

  public MikanVector3d() : this(MikanClientPINVOKE.new_MikanVector3d(), true) {
  }

}

}
