//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanMonoIntrinsics : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanMonoIntrinsics(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanMonoIntrinsics obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanMonoIntrinsics obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanMonoIntrinsics() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanMonoIntrinsics(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double pixel_width {
    set {
      MikanClientPINVOKE.MikanMonoIntrinsics_pixel_width_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMonoIntrinsics_pixel_width_get(swigCPtr);
      return ret;
    } 
  }

  public double pixel_height {
    set {
      MikanClientPINVOKE.MikanMonoIntrinsics_pixel_height_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMonoIntrinsics_pixel_height_get(swigCPtr);
      return ret;
    } 
  }

  public double hfov {
    set {
      MikanClientPINVOKE.MikanMonoIntrinsics_hfov_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMonoIntrinsics_hfov_get(swigCPtr);
      return ret;
    } 
  }

  public double vfov {
    set {
      MikanClientPINVOKE.MikanMonoIntrinsics_vfov_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMonoIntrinsics_vfov_get(swigCPtr);
      return ret;
    } 
  }

  public double znear {
    set {
      MikanClientPINVOKE.MikanMonoIntrinsics_znear_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMonoIntrinsics_znear_get(swigCPtr);
      return ret;
    } 
  }

  public double zfar {
    set {
      MikanClientPINVOKE.MikanMonoIntrinsics_zfar_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMonoIntrinsics_zfar_get(swigCPtr);
      return ret;
    } 
  }

  public MikanDistortionCoefficients distortion_coefficients {
    set {
      MikanClientPINVOKE.MikanMonoIntrinsics_distortion_coefficients_set(swigCPtr, MikanDistortionCoefficients.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanMonoIntrinsics_distortion_coefficients_get(swigCPtr);
      MikanDistortionCoefficients ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanDistortionCoefficients(cPtr, false);
      return ret;
    } 
  }

  public MikanMatrix3d camera_matrix {
    set {
      MikanClientPINVOKE.MikanMonoIntrinsics_camera_matrix_set(swigCPtr, MikanMatrix3d.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanMonoIntrinsics_camera_matrix_get(swigCPtr);
      MikanMatrix3d ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanMatrix3d(cPtr, false);
      return ret;
    } 
  }

  public MikanMonoIntrinsics() : this(MikanClientPINVOKE.new_MikanMonoIntrinsics(), true) {
  }

}

}
