//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanVideoSourceNewFrameEvent : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanVideoSourceNewFrameEvent(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanVideoSourceNewFrameEvent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanVideoSourceNewFrameEvent obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanVideoSourceNewFrameEvent() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanVideoSourceNewFrameEvent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MikanVector3f cameraForward {
    set {
      MikanClientPINVOKE.MikanVideoSourceNewFrameEvent_cameraForward_set(swigCPtr, MikanVector3f.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanVideoSourceNewFrameEvent_cameraForward_get(swigCPtr);
      MikanVector3f ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanVector3f(cPtr, false);
      return ret;
    } 
  }

  public MikanVector3f cameraUp {
    set {
      MikanClientPINVOKE.MikanVideoSourceNewFrameEvent_cameraUp_set(swigCPtr, MikanVector3f.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanVideoSourceNewFrameEvent_cameraUp_get(swigCPtr);
      MikanVector3f ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanVector3f(cPtr, false);
      return ret;
    } 
  }

  public MikanVector3f cameraPosition {
    set {
      MikanClientPINVOKE.MikanVideoSourceNewFrameEvent_cameraPosition_set(swigCPtr, MikanVector3f.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanVideoSourceNewFrameEvent_cameraPosition_get(swigCPtr);
      MikanVector3f ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanVector3f(cPtr, false);
      return ret;
    } 
  }

  public ulong frame {
    set {
      MikanClientPINVOKE.MikanVideoSourceNewFrameEvent_frame_set(swigCPtr, value);
    } 
    get {
      ulong ret = MikanClientPINVOKE.MikanVideoSourceNewFrameEvent_frame_get(swigCPtr);
      return ret;
    } 
  }

  public MikanVideoSourceNewFrameEvent() : this(MikanClientPINVOKE.new_MikanVideoSourceNewFrameEvent(), true) {
  }

}

}
