//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanRenderTargetDescriptor : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanRenderTargetDescriptor(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanRenderTargetDescriptor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanRenderTargetDescriptor obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanRenderTargetDescriptor() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanRenderTargetDescriptor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MikanColorBufferType color_buffer_type {
    set {
      MikanClientPINVOKE.MikanRenderTargetDescriptor_color_buffer_type_set(swigCPtr, (int)value);
    } 
    get {
      MikanColorBufferType ret = (MikanColorBufferType)MikanClientPINVOKE.MikanRenderTargetDescriptor_color_buffer_type_get(swigCPtr);
      return ret;
    } 
  }

  public MikanColorRGB color_key {
    set {
      MikanClientPINVOKE.MikanRenderTargetDescriptor_color_key_set(swigCPtr, MikanColorRGB.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanRenderTargetDescriptor_color_key_get(swigCPtr);
      MikanColorRGB ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanColorRGB(cPtr, false);
      return ret;
    } 
  }

  public MikanDepthBufferType depth_buffer_type {
    set {
      MikanClientPINVOKE.MikanRenderTargetDescriptor_depth_buffer_type_set(swigCPtr, (int)value);
    } 
    get {
      MikanDepthBufferType ret = (MikanDepthBufferType)MikanClientPINVOKE.MikanRenderTargetDescriptor_depth_buffer_type_get(swigCPtr);
      return ret;
    } 
  }

  public uint width {
    set {
      MikanClientPINVOKE.MikanRenderTargetDescriptor_width_set(swigCPtr, value);
    } 
    get {
      uint ret = MikanClientPINVOKE.MikanRenderTargetDescriptor_width_get(swigCPtr);
      return ret;
    } 
  }

  public uint height {
    set {
      MikanClientPINVOKE.MikanRenderTargetDescriptor_height_set(swigCPtr, value);
    } 
    get {
      uint ret = MikanClientPINVOKE.MikanRenderTargetDescriptor_height_get(swigCPtr);
      return ret;
    } 
  }

  public MikanClientGraphicsApi graphicsAPI {
    set {
      MikanClientPINVOKE.MikanRenderTargetDescriptor_graphicsAPI_set(swigCPtr, (int)value);
    } 
    get {
      MikanClientGraphicsApi ret = (MikanClientGraphicsApi)MikanClientPINVOKE.MikanRenderTargetDescriptor_graphicsAPI_get(swigCPtr);
      return ret;
    } 
  }

  public MikanRenderTargetDescriptor() : this(MikanClientPINVOKE.new_MikanRenderTargetDescriptor(), true) {
  }

}

}
