//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanDistortionCoefficients : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanDistortionCoefficients(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanDistortionCoefficients obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanDistortionCoefficients obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanDistortionCoefficients() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanDistortionCoefficients(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double k1 {
    set {
      MikanClientPINVOKE.MikanDistortionCoefficients_k1_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanDistortionCoefficients_k1_get(swigCPtr);
      return ret;
    } 
  }

  public double k2 {
    set {
      MikanClientPINVOKE.MikanDistortionCoefficients_k2_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanDistortionCoefficients_k2_get(swigCPtr);
      return ret;
    } 
  }

  public double k3 {
    set {
      MikanClientPINVOKE.MikanDistortionCoefficients_k3_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanDistortionCoefficients_k3_get(swigCPtr);
      return ret;
    } 
  }

  public double k4 {
    set {
      MikanClientPINVOKE.MikanDistortionCoefficients_k4_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanDistortionCoefficients_k4_get(swigCPtr);
      return ret;
    } 
  }

  public double k5 {
    set {
      MikanClientPINVOKE.MikanDistortionCoefficients_k5_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanDistortionCoefficients_k5_get(swigCPtr);
      return ret;
    } 
  }

  public double k6 {
    set {
      MikanClientPINVOKE.MikanDistortionCoefficients_k6_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanDistortionCoefficients_k6_get(swigCPtr);
      return ret;
    } 
  }

  public double p1 {
    set {
      MikanClientPINVOKE.MikanDistortionCoefficients_p1_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanDistortionCoefficients_p1_get(swigCPtr);
      return ret;
    } 
  }

  public double p2 {
    set {
      MikanClientPINVOKE.MikanDistortionCoefficients_p2_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanDistortionCoefficients_p2_get(swigCPtr);
      return ret;
    } 
  }

  public MikanDistortionCoefficients() : this(MikanClientPINVOKE.new_MikanDistortionCoefficients(), true) {
  }

}

}
