//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanEvent_event_payload : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanEvent_event_payload(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanEvent_event_payload obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanEvent_event_payload obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanEvent_event_payload() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanEvent_event_payload(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MikanVideoSourceNewFrameEvent video_source_new_frame {
    set {
      MikanClientPINVOKE.MikanEvent_event_payload_video_source_new_frame_set(swigCPtr, MikanVideoSourceNewFrameEvent.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanEvent_event_payload_video_source_new_frame_get(swigCPtr);
      MikanVideoSourceNewFrameEvent ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanVideoSourceNewFrameEvent(cPtr, false);
      return ret;
    } 
  }

  public MikanVRDevicePoseUpdateEvent vr_device_pose_updated {
    set {
      MikanClientPINVOKE.MikanEvent_event_payload_vr_device_pose_updated_set(swigCPtr, MikanVRDevicePoseUpdateEvent.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanEvent_event_payload_vr_device_pose_updated_get(swigCPtr);
      MikanVRDevicePoseUpdateEvent ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanVRDevicePoseUpdateEvent(cPtr, false);
      return ret;
    } 
  }

  public MikanAnchorPoseUpdateEvent anchor_pose_updated {
    set {
      MikanClientPINVOKE.MikanEvent_event_payload_anchor_pose_updated_set(swigCPtr, MikanAnchorPoseUpdateEvent.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanEvent_event_payload_anchor_pose_updated_get(swigCPtr);
      MikanAnchorPoseUpdateEvent ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanAnchorPoseUpdateEvent(cPtr, false);
      return ret;
    } 
  }

  public MikanScriptMessageInfo script_message_posted {
    set {
      MikanClientPINVOKE.MikanEvent_event_payload_script_message_posted_set(swigCPtr, MikanScriptMessageInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanEvent_event_payload_script_message_posted_get(swigCPtr);
      MikanScriptMessageInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanScriptMessageInfo(cPtr, false);
      return ret;
    } 
  }

  public MikanEvent_event_payload() : this(MikanClientPINVOKE.new_MikanEvent_event_payload(), true) {
  }

}

}
