//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanVideoSourceAttachmentInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanVideoSourceAttachmentInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanVideoSourceAttachmentInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanVideoSourceAttachmentInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanVideoSourceAttachmentInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanVideoSourceAttachmentInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int parent_anchor_id {
    set {
      MikanClientPINVOKE.MikanVideoSourceAttachmentInfo_parent_anchor_id_set(swigCPtr, value);
    } 
    get {
      int ret = MikanClientPINVOKE.MikanVideoSourceAttachmentInfo_parent_anchor_id_get(swigCPtr);
      return ret;
    } 
  }

  public int attached_vr_device_id {
    set {
      MikanClientPINVOKE.MikanVideoSourceAttachmentInfo_attached_vr_device_id_set(swigCPtr, value);
    } 
    get {
      int ret = MikanClientPINVOKE.MikanVideoSourceAttachmentInfo_attached_vr_device_id_get(swigCPtr);
      return ret;
    } 
  }

  public MikanMatrix4f vr_device_offset_xform {
    set {
      MikanClientPINVOKE.MikanVideoSourceAttachmentInfo_vr_device_offset_xform_set(swigCPtr, MikanMatrix4f.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanVideoSourceAttachmentInfo_vr_device_offset_xform_get(swigCPtr);
      MikanMatrix4f ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanMatrix4f(cPtr, false);
      return ret;
    } 
  }

  public float camera_scale {
    set {
      MikanClientPINVOKE.MikanVideoSourceAttachmentInfo_camera_scale_set(swigCPtr, value);
    } 
    get {
      float ret = MikanClientPINVOKE.MikanVideoSourceAttachmentInfo_camera_scale_get(swigCPtr);
      return ret;
    } 
  }

  public MikanVideoSourceAttachmentInfo() : this(MikanClientPINVOKE.new_MikanVideoSourceAttachmentInfo(), true) {
  }

}

}
