//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public enum MikanResult {
  Success = 0,
  GeneralError = -1,
  Uninitialized = -2,
  NullParam = -2,
  InitFailed = -3,
  ConnectionFailed = -4,
  AlreadyConnected = -5,
  NoData = -6,
  NotConnected = -7,
  SharedMemoryError = -8,
  UnknownClient = -9,
  UnknownFunction = -10,
  FailedFunctionSend = -11,
  FunctionResponseTimeout = -12,
  MalformedParameters = -13,
  MalformedResponse = -14,
  NoSelectedCamera = -15,
  NoCameraAssignedTracker = -16,
  InvalidDeviceID = -17,
  InvalidStencilID = -18,
  TooManyStencils = -19,
  InvalidAPI = -20,
  SharedTextureError = -21,
  InvalidAnchorID = -22
}

}
