//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanRotator3f : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanRotator3f(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanRotator3f obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanRotator3f obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanRotator3f() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanRotator3f(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float x_angle {
    set {
      MikanClientPINVOKE.MikanRotator3f_x_angle_set(swigCPtr, value);
    } 
    get {
      float ret = MikanClientPINVOKE.MikanRotator3f_x_angle_get(swigCPtr);
      return ret;
    } 
  }

  public float y_angle {
    set {
      MikanClientPINVOKE.MikanRotator3f_y_angle_set(swigCPtr, value);
    } 
    get {
      float ret = MikanClientPINVOKE.MikanRotator3f_y_angle_get(swigCPtr);
      return ret;
    } 
  }

  public float z_angle {
    set {
      MikanClientPINVOKE.MikanRotator3f_z_angle_set(swigCPtr, value);
    } 
    get {
      float ret = MikanClientPINVOKE.MikanRotator3f_z_angle_get(swigCPtr);
      return ret;
    } 
  }

  public MikanRotator3f() : this(MikanClientPINVOKE.new_MikanRotator3f(), true) {
  }

}

}
