//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public enum MikanClientGraphicsApi {
  UNKNOWN,
  Direct3D9,
  Direct3D11,
  Direct3D12,
  OpenGL,
  COUNT
}

}
