//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanVideoSourceIntrinsics : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanVideoSourceIntrinsics(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanVideoSourceIntrinsics obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanVideoSourceIntrinsics obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanVideoSourceIntrinsics() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanVideoSourceIntrinsics(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MikanVideoSourceIntrinsics_intrinsics intrinsics {
    get {
      global::System.IntPtr cPtr = MikanClientPINVOKE.MikanVideoSourceIntrinsics_intrinsics_get(swigCPtr);
      MikanVideoSourceIntrinsics_intrinsics ret = (cPtr == global::System.IntPtr.Zero) ? null : new MikanVideoSourceIntrinsics_intrinsics(cPtr, false);
      return ret;
    } 
  }

  public MikanIntrinsicsType intrinsics_type {
    set {
      MikanClientPINVOKE.MikanVideoSourceIntrinsics_intrinsics_type_set(swigCPtr, (int)value);
    } 
    get {
      MikanIntrinsicsType ret = (MikanIntrinsicsType)MikanClientPINVOKE.MikanVideoSourceIntrinsics_intrinsics_type_get(swigCPtr);
      return ret;
    } 
  }

  public MikanVideoSourceIntrinsics() : this(MikanClientPINVOKE.new_MikanVideoSourceIntrinsics(), true) {
  }

}

}
