//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Mikan {

public class MikanMatrix4x3d : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MikanMatrix4x3d(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MikanMatrix4x3d obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MikanMatrix4x3d obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MikanMatrix4x3d() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MikanClientPINVOKE.delete_MikanMatrix4x3d(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double x0 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_x0_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_x0_get(swigCPtr);
      return ret;
    } 
  }

  public double x1 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_x1_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_x1_get(swigCPtr);
      return ret;
    } 
  }

  public double x2 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_x2_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_x2_get(swigCPtr);
      return ret;
    } 
  }

  public double x3 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_x3_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_x3_get(swigCPtr);
      return ret;
    } 
  }

  public double y0 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_y0_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_y0_get(swigCPtr);
      return ret;
    } 
  }

  public double y1 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_y1_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_y1_get(swigCPtr);
      return ret;
    } 
  }

  public double y2 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_y2_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_y2_get(swigCPtr);
      return ret;
    } 
  }

  public double y3 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_y3_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_y3_get(swigCPtr);
      return ret;
    } 
  }

  public double z0 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_z0_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_z0_get(swigCPtr);
      return ret;
    } 
  }

  public double z1 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_z1_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_z1_get(swigCPtr);
      return ret;
    } 
  }

  public double z2 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_z2_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_z2_get(swigCPtr);
      return ret;
    } 
  }

  public double z3 {
    set {
      MikanClientPINVOKE.MikanMatrix4x3d_z3_set(swigCPtr, value);
    } 
    get {
      double ret = MikanClientPINVOKE.MikanMatrix4x3d_z3_get(swigCPtr);
      return ret;
    } 
  }

  public MikanMatrix4x3d() : this(MikanClientPINVOKE.new_MikanMatrix4x3d(), true) {
  }

}

}
